name: Build Java project with Maven
 
on: [push, pull_request]
 
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
  send_telegram:
   name: send telegram
   needs: build_linux
   runs-on: ubuntu-latest
   steps:
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: DevOps_lab-1.0-SNAPSHOT.jar
          message: |
            Below you can see the build file:
