name: Build sample Java Maven project
 
on: [push, pull_request]
 
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
  send_telegram:
   name: send telegram
   needs: build_linux
   runs-on: ubuntu-latest
   steps:
     - uses: actions/download-artifact@v3
       with:
         name: Package
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: staging/Package.zip
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
