name: Build Java project with Maven
 
on: workflow_dispatch
 
jobs:
  build_linux:
   name: build for Linux
   runs-on: ubuntu-latest
   steps:
    - name: Getting repository code
      uses: actions/checkout@v3
    - name: Sett-upping Java
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Building with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Creating directory for the artifacts
      run: mkdir staging && cp target/*.jar staging
    - name: uploading artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
  send_telegram:
   name: send telegram
   needs: build_linux
   runs-on: ubuntu-latest
   steps:
     - uses: actions/download-artifact@v3
       with:
         name: Package
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: DevOps_lab-1.0-SNAPSHOT.jar
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Also below you can see the build file:
  formatting:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v3
         with:
           java-version: '19'
           distribution: 'temurin'
       - uses: axel-op/googlejavaformat-action@v3
         with:
           args: "--replace"
           skip-commit: true
       - name: Print diffs
         run: git --no-pager diff --exit-code
